### ISSUE TITLE
GTS metrics: Graph axis titles

### ISSUE THREAD

**Issue by kbailey-noaa** [ioos/ioos_metrics#27]
https://ioos.github.io/ioos_metrics/gts_regional.html

I don't think the bar graphs show "Regional Messages"  as titled.  Recommend changing to # IOOS Regional Observations.  The NDBC reports are communicating # observations, not messages.  I think the actual GTS messages contain several stations / obs, which we don't see.

**Comment by MathewBiddle** [comment]
Good catch. 

I was using the text from https://www.ndbc.noaa.gov/ioosstats/ which says "The GTS monthly reports show the number of messages released to the GTS for each station."

Should that page be updated as well?
