### ISSUE TITLE
create mamba/conda environment instead of pip install

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_metrics#46]
Should simplify the action for website build and deployment: https://github.com/ioos/ioos_metrics/blob/a4dcd2f19d65d96b2fc36b6d48a7f91685a9dd09/.github/workflows/website_create_and_deploy.yml#L21-L28

**Comment by ocefpaf** [comment]
Websites and apps should always "lock" the dependencies used in the build. We can go for a conda-lock file or use the shiny and new pixi. I can send a PR if you want.

**Comment by ocefpaf** [comment]
I believe this one can be closed. It was addressed in https://github.com/ioos/ioos_metrics/pull/42

That env may require a update though.
