### ISSUE TITLE
Collect MBON dataset DOI, download, and use statistics from OBIS and GBIF API

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_metrics#69]
I wrote a clunky python notebook here https://github.com/MathewBiddle/sandbox/blob/main/notebooks/MBON_OBIS_statistics.ipynb

@sformel-usgs wrote something in R I believe. 

![image](https://github.com/ioos/ioos_metrics/assets/8480023/d524871e-7a57-4b70-8756-9db4b6e0eb5b)

![image](https://github.com/ioos/ioos_metrics/assets/8480023/6cf87724-d0e4-42eb-b42f-04ba4f47d95d)

**Comment by MathewBiddle** [comment]
xref: 
* https://github.com/ioos/mbon-docs/issues/45

**Comment by MathewBiddle** [comment]
Code from Steve: 
[xmbon_stats.zip](https://github.com/ioos/ioos_metrics/files/15297426/xmbon_stats.zip)

**Comment by MathewBiddle** [comment]
@laurabrenskelle Should we write something in python or R? We have the start to both options.

**Comment by MathewBiddle** [comment]
My vote is for python because it would be easier to add to the ioos_metrics library.

**Comment by laurabrenskelle** [comment]
Sure, I think both options will work. I am more familiar with R, but since we have starts for both and the ioos_metrics library is in python, python seems like a good choice.

**Comment by MathewBiddle** [comment]
Tasks:

- [ ] run Steve's R
- [ ] Run Matt's python
- [ ] Compare results
- [ ] Update python to align with Steve's code
- [ ] Migrate Python code as function to ioos_metrics

**Comment by MathewBiddle** [comment]
Just found this: https://pygbif.readthedocs.io/en/latest/index.html maybe pygbif is the right approach?

**Comment by MathewBiddle** [comment]
xref: https://github.com/ioos/ioos_metrics/pull/74
