### ISSUE TITLE
Publish to pypi failed for release v0.2.0a0

### ISSUE THREAD

**Issue by MathewBiddle** [ioos/ioos_metrics#82]
See https://github.com/ioos/ioos_metrics/actions/runs/9303383501

It looks like we need to set permissions in https://github.com/ioos/ioos_metrics/blob/main/.github/workflows/pypi.yml?

**Comment by MathewBiddle** [comment]
cc @ocefpaf

**Comment by ocefpaf** [comment]
I thought I mentioned this to you on slack or in another issue but I do have enough rights here to add the token. That is why I added you to the PyPI package. I guess that only you have enough privileges in this repo to do that.

**Comment by ocefpaf** [comment]
Matt, do we have the PyPI token in this repo? I don't have adim rights here, so I can't do it. I'm pushing a new release manually for now to help Mary with the glider names.

**Comment by MathewBiddle** [comment]
I think this is fixed.
https://github.com/ioos/ioos_metrics/actions/runs/11185529098

**Comment by MathewBiddle** [comment]
See v0.5.0 at https://pypi.org/project/ioos-metrics/

**Comment by ocefpaf** [comment]
It worked! We can close this one.
